### ISSUE TITLE
Critical _System Blue screen 

### ISSUE THREAD

**Issue by programming2012** [hyperbox/vbox-5.1#1]
System：Windows 10 Professional x64 (10.0 Version 14393)
VirtualBox:VirtualBox-5.1.6-110634-Win

The installation process is normal.
VirtualBox Start normal.
When start virtual comptuter ,The system exits directly，Blue scren.
                                 thanks

![default](https://cloud.githubusercontent.com/assets/22572617/19376266/e30a20a0-920e-11e6-8a90-6f465bc89c1f.png)

**Comment by maxidorius** [comment]
Could you post:
- The version of Hyperbox you are using in the "About" dialog of the client
- The exact english error message/code of the blue screen
- The VBox.log for the concerned VM
- The VM config (.vbox file)

Without those, we won't be able to troubleshoot anything. Thanks!

**Comment by programming2012** [comment]
Hello
*About The version of Hyperbox,I could not find it ,this is the Screenshot，See if there is any information you need
![image](https://cloud.githubusercontent.com/assets/22572617/20030936/338bc004-a3aa-11e6-9acb-79bc17dfc82f.png)
*The exact english error message/code of the blue screen is:  
Stop Code: SYSTEM SERVICE EXCEPTION
*About VBox.log And VM config:
[LogAndConfig.zip](https://github.com/hyperbox/vbox-5.1/files/573307/LogAndConfig.zip)

Thanks!

**Comment by maxidorius** [comment]
Can you start the same VM (not a copy!) with the exact same config without hyperbox?

**Comment by programming2012** [comment]
**After close Hyper-V,VirtualBox Can use,
like this:**

![default](https://cloud.githubusercontent.com/assets/22572617/20085112/90e85dfe-a5a1-11e6-99fa-db255402a402.png)

**Comment by maxidorius** [comment]
Glad you solved it! Hyper-V must indeed by removed before using VirtualBox as Hyper-V is not playing nice.
